{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal-demo.tlsSecretName" . }}
type: Opaque
stringData:
  {{ .Values.tls.certKeys.ca }}: |
{{ required "Set tls.certData.ca when tls.create=true" .Values.tls.certData.ca | indent 4 }}
  {{ .Values.tls.certKeys.serverCert }}: |
{{ required "Set tls.certData.serverCert when tls.create=true" .Values.tls.certData.serverCert | indent 4 }}
  {{ .Values.tls.certKeys.serverKey }}: |
{{ required "Set tls.certData.serverKey when tls.create=true" .Values.tls.certData.serverKey | indent 4 }}
  {{ .Values.tls.certKeys.clientCert }}: |
{{ required "Set tls.certData.clientCert when tls.create=true" .Values.tls.certData.clientCert | indent 4 }}
  {{ .Values.tls.certKeys.clientKey }}: |
{{ required "Set tls.certData.clientKey when tls.create=true" .Values.tls.certData.clientKey | indent 4 }}
{{- end }}
