{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: temporal-auth
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ required "Set auth.token or provide auth.existingSecret" .Values.auth.token | quote }}
{{- end }}
