tls:
  existingSecret: "temporal-tls-certs"
  secretName: temporal-tls-certs
  create: false
  requireClientAuth: false
  frontendServerName: temporal
  mtlsEnabled: true
  useClientCert: false
  internodeDisableHostVerification: true
  frontendDisableHostVerification: true
  certKeys:
    ca: ca.crt
    serverCert: server.crt
    serverKey: server.key
    clientCert: client.crt
    clientKey: client.key
  certData:
    ca: ""
    serverCert: ""
    serverKey: ""
    clientCert: ""
    clientKey: ""

images:
  postgres:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  temporal:
    repository: temporalio/server
    tag: "1.26.2"
    pullPolicy: IfNotPresent
  temporalAdminTools:
    repository: temporalio/admin-tools
    tag: "1.26.2"
    pullPolicy: IfNotPresent
  temporalUi:
    repository: temporalio/ui
    tag: "2.31.2"
    pullPolicy: IfNotPresent
  app:
    repository: temporal-demo-app
    tag: "latest"
    pullPolicy: IfNotPresent

postgres:
  user: temporal
  password: temporal
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

temporal:
  db: postgres12
  dbPort: "5432"
  dynamicConfigFilePath: /etc/temporal/config/dynamicconfig/docker.yaml
  useInternalFrontend: true
  namespace:
    name: default
    retention: 72h
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 1536Mi

temporalUi:
  temporalAddress: temporal:7233
  corsOrigins: http://localhost:8081
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: null

app:
  taskQueue: demo-task-queue
  temporalTargetHost: temporal:7233
  web:
    command:
      - uvicorn
      - temporal_demo.api:app
      - --host
      - 0.0.0.0
      - --port
      - "8080"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    service:
      type: NodePort
      port: 8080
      targetPort: 8080
      nodePort: null
  worker:
    command:
      - python
      - -m
      - temporal_demo.worker
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
