from __future__ import annotations

import os


TEMPORAL_TARGET_HOST = os.getenv("TEMPORAL_TARGET_HOST", "localhost:7233")
TEMPORAL_TASK_QUEUE = os.getenv("TEMPORAL_TASK_QUEUE", "demo-task-queue")
TEMPORAL_MTLS_ENABLED = os.getenv("TEMPORAL_MTLS_ENABLED", "false").lower() in {
	"1",
	"true",
	"yes",
	"on",
}
TEMPORAL_TLS_DOMAIN = os.getenv("TEMPORAL_TLS_DOMAIN", "")
TEMPORAL_TLS_CA_CERT_PATH = os.getenv("TEMPORAL_TLS_CA_CERT_PATH", "")
TEMPORAL_TLS_CLIENT_CERT_PATH = os.getenv("TEMPORAL_TLS_CLIENT_CERT_PATH", "")
TEMPORAL_TLS_CLIENT_KEY_PATH = os.getenv("TEMPORAL_TLS_CLIENT_KEY_PATH", "")
TEMPORAL_CONNECT_RETRIES = int(os.getenv("TEMPORAL_CONNECT_RETRIES", "20"))
TEMPORAL_CONNECT_DELAY_SECONDS = float(os.getenv("TEMPORAL_CONNECT_DELAY_SECONDS", "3"))

