apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-ui-ingress
  namespace: temporal-demo
spec:
  ingressClassName: nginx
  rules:
    - host: temporal-ui.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-ui
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-grpc-ingress
  namespace: temporal-demo
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: temporal-grpc.minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal
                port:
                  number: 7233